FROM library/centos:7

ARG PDK_URL=https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=el&rel=7&arch=x86_64&ver=latest

RUN curl -LOJ "${PDK_URL}" \
 && yum install pdk*.rpm \
 && rm -f pdk*.rpm \
 && yum clean all \
 && rm -rf /var/cache/yum

